### ISSUE TITLE
Appinstaller schema invalid when "Update on Launch" selected in DevOps extension

### ISSUE THREAD

**Issue by mtbayley** [microsoft/msix-packaging#405]
*Project*
MSIX Packaging Extension (DevOps)

**Describe the bug**
When creating the appinstaller file through a CI pipeline, the resulting file is invalid for installing a new application.

> App installation failed with error message: error 0xC00CE018: App manifest validation error: The app manifest must be valid as per schema: Line 5, Column 6, Reason: Text is not allowed in the context of element '{http://schemas.microsoft.com/appx/appinstaller/2018}OnLaunch' according to DTD/Schema. (0xc00ce018)

**To Reproduce**
Create a AppInstallerFile@1 task in yaml. Set the update options.

**Expected behavior**
Appinstaller file should install the application

**Screenshots**
![image](https://user-images.githubusercontent.com/34929316/103919108-a7e92100-50dd-11eb-8ac9-07780650f7f1.png)
![image](https://user-images.githubusercontent.com/34929316/103919654-4aa19f80-50de-11eb-88b5-b4d2a1fc77d9.png)

**Platform**
windows-latest

**Additional context**

Resulting appinstaller file:
```
<UpdateSettings>
  <OnLaunch>
    <HoursBetweenUpdateChecks>24</HoursBetweenUpdateChecks>
    <ShowPrompt>true</ShowPrompt>
    <UpdateBlocksActivation>true</UpdateBlocksActivation>
  </OnLaunch>
</UpdateSettings>
```
As a workaround, I changed the elements to attributes on OnLaunch. This resolved the error

```
<UpdateSettings>
    <OnLaunch HoursBetweenUpdateChecks="24" ShowPrompt="true" UpdateBlocksActivation="true" />
</UpdateSettings>
```
According to: [https://docs.microsoft.com/en-us/uwp/schemas/appinstallerschema/element-onlaunch](url)
On Launch should have attributes, not elements

**Comment by lechacon** [comment]
This should be fixed in the code now but not yet published to the marketplace. Will update when it is available.

**Comment by lechacon** [comment]
@mtbayley This should work now in the latest version of the extension (1.0.4). Please let me know if you still this issue.

**Comment by mtbayley** [comment]
@lechacon Still having the same result in 1.0.4

![image](https://user-images.githubusercontent.com/34929316/104034646-29ed4e80-519f-11eb-9bb7-c02457ee189b.png)
![image](https://user-images.githubusercontent.com/34929316/104034986-9b2d0180-519f-11eb-8b76-2db1300e8f25.png)

**Comment by lechacon** [comment]
@mtbayley Sorry for the late reply. Are you still seeing this? What version of the task do you see in the logs during a run of the pipeline?
![image](https://user-images.githubusercontent.com/14323496/105118608-a0355f00-5a83-11eb-9613-35f076abdee0.png)

I tested it and got the right result. I ask for the version of the task as I've seen it use an older version of the task even if the newer version of the extension is listed as installed. Uninstalling and installing the extension again may force using the right version of the task.

**Comment by mtbayley** [comment]
@lechacon That did it. Now I'm running 1.0.6. Tested with pipeline and it works.

Thanks again

**Comment by lechacon** [comment]
Good to hear. I'll close this issue.
